#cloud-config

#coreos Configuration setup on bootup
coreos:
  etcd2:
    # generate a new token for each unique cluster from https://discovery.etcd.io/new?size=3
    # discovery: "https://discovery.etcd.io/<token>"
    discovery: https://discovery.etcd.io/ef4cb99544c1905c54eedf2221877345
    # multi-region and multi-cloud deployments need to use $public_ipv4
    advertise-client-urls: "http://$public_ipv4:2379"
    initial-advertise-peer-urls: "http://$private_ipv4:2380"
    # listen on both the official ports and the legacy port
    # legacy ports can be omitted if your application doesn't depend on them
    listen-client-urls: "http://0.0.0.0:2379,http://0.0.0.0:4001"
    listen-peer-urls: "http://$private_ipv4:2380,http://$private_ipv4:7001"
    
  fleet:
    public-ip: $public_ipv4
    
  units:
    - name: "etcd2.service"
      command: "start"

    - name: "fleet.service"
      command: "start"

    - name: "docker-tcp.socket"
      command: "start"
      enable: true
      content: |
        [Unit]
        Description=Docker Socket for the API
        [Socket]
        ListenStream=2375
        BindIPv6Only=both
        Service=docker.service
        [Install]
        WantedBy=sockets.target
       
    - name: jenkins-ruby.service
      command: start
      runtime: no
      content: |
        [Unit]
        Description=jenkins-ruby
        After=docker.service
        Requires=docker.service
        
        [Service]
        User=coreos1Jenkins
        TimeoutStartSec=0
        ExecStartPre=-/usr/bin/docker build -t coreos1Jenkins/jenkins-srv /home/core/jenkins-srv
        ExecStartPre=-/usr/bin/docker rm -f jenkins 
        ExecStart=/usr/bin/docker run -p 8080:8080 -p 50000:50000 --name jenkins -v /var/log/.jenkins:/root/.jenkins:rw coreos1Jenkins/jenkins-srv
        ExecStop=/usr/bin/docker stop jenkins
        Restart=always
        
        [Install]
        WantedBy=local.target
        
hostname: jenkins

users:
  - name: coreos1Jenkins
    passwd: July@2017
    groups:
      - sudo
      - docker
