#cloud-config

#coreos Configuration setup on bootup
coreos:
  etcd2:
    # generate a new token for each unique cluster from https://discovery.etcd.io/new?size=3
    # discovery: "https://discovery.etcd.io/new?size=3"
    discovery: https://discovery.etcd.io/8e63b12b8ce33cdb8550016331746622
    # multi-region and multi-cloud deployments need to use $public_ipv4
    advertise-client-urls: "http://$public_ipv4:2379"
    initial-advertise-peer-urls: "http://$private_ipv4:2380"
    # listen on both the official ports and the legacy port
    # legacy ports can be omitted if your application doesn't depend on them
    listen-client-urls: "http://0.0.0.0:2379,http://0.0.0.0:4001"
    listen-peer-urls: "http://$private_ipv4:2380,http://$private_ipv4:7001"
    
  fleet:
    public-ip: $public_ipv4
    
  units:
    - name: "etcd2.service"
      command: "start"

    - name: "fleet.service"
      command: "start"

users:
  - name: venkatesh
    groups:
      - sudo
      - docker
    ssh_authorized_keys:
      - "ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABAQDGyEOBTkz4V/U1c44rVRNY+LB6Vpo0DgVNSPq8NvefB7TRLlg72dEbYQDJKMrSSGyFP6wwUpZ2i7zsfneeYHi65h0mY9z9onAacG5jPffqf5jpiK7IZXVQXJNMefurt3RPHDEBuZTMIDLttEBEcxmRPUBL7ejO8bq362/drkY1ZyYxnkOd3++hTFjOGQOuruzrrMN6LXYAn+K50cx1zZe6qg1ZgKaZOea0tss0D9Tg9P0DltxpNChWS0N3Jq/igNj9TWBBd1/oiu/tKD+UhI3Tn20CNoF8PgLuHrYCKbDNf3HgRLA9W4M0ZXKp9OJfia4zT0CKLCaYvYlwPcCFR7UX v-venchu@MININT-54FSVBF"

